import jsPDF from 'jspdf';

const PURPLE = [124, 58, 237];
const CYAN   = [6, 182, 212];
const DARK   = [30, 30, 50];
const GREY   = [100, 100, 120];
const LIGHT  = [240, 240, 248];

const PAGE_W  = 210; // A4 mm
const MARGIN  = 18;
const CONTENT = PAGE_W - MARGIN * 2;

export function exportItineraryPDF(trip) {
  const { itinerary, startDate, endDate, budget, destination } = trip;
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const PH = doc.internal.pageSize.getHeight();
  let y = 0;

  function newPage() {
    doc.addPage();
    y = MARGIN;
    // subtle header line on new pages
    doc.setDrawColor(...PURPLE);
    doc.setLineWidth(0.5);
    doc.line(MARGIN, 10, PAGE_W - MARGIN, 10);
  }

  function checkY(needed = 10) {
    if (y + needed > PH - MARGIN) newPage();
  }

  function heading1(text) {
    checkY(14);
    doc.setFontSize(20);
    doc.setTextColor(...PURPLE);
    doc.setFont(undefined, 'bold');
    doc.text(text, MARGIN, y);
    y += 8;
    doc.setDrawColor(...CYAN);
    doc.setLineWidth(0.4);
    doc.line(MARGIN, y, MARGIN + 60, y);
    y += 5;
  }

  function heading2(text, color = DARK) {
    checkY(10);
    doc.setFontSize(13);
    doc.setTextColor(...color);
    doc.setFont(undefined, 'bold');
    doc.text(text, MARGIN, y);
    y += 6;
  }

  function body(text, indent = 0, color = DARK) {
    doc.setFontSize(9.5);
    doc.setTextColor(...color);
    doc.setFont(undefined, 'normal');
    const lines = doc.splitTextToSize(text, CONTENT - indent);
    checkY(lines.length * 4.5);
    doc.text(lines, MARGIN + indent, y);
    y += lines.length * 4.5;
  }

  function badge(label, x, bY, bgColor = PURPLE) {
    const w = doc.getTextWidth(label) + 6;
    doc.setFillColor(...bgColor);
    doc.roundedRect(x, bY - 3.5, w, 5, 1.5, 1.5, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(7.5);
    doc.setFont(undefined, 'bold');
    doc.text(label, x + 3, bY);
    return w + 2;
  }

  function divider() {
    checkY(6);
    doc.setDrawColor(...LIGHT);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 4;
  }

  // ── Cover ──────────────────────────────────────────────────────────────────
  doc.setFillColor(...DARK);
  doc.rect(0, 0, PAGE_W, 55, 'F');

  doc.setFillColor(...PURPLE);
  doc.circle(PAGE_W - 20, 10, 35, 'F');
  doc.setFillColor(...CYAN[0], ...CYAN.slice(1));
  doc.setFillColor(6, 182, 212);
  doc.circle(20, 55, 20, 'F');

  doc.setFontSize(26);
  doc.setTextColor(255, 255, 255);
  doc.setFont(undefined, 'bold');
  doc.text(itinerary.destination || destination, MARGIN, 28);

  doc.setFontSize(10);
  doc.setTextColor(200, 200, 220);
  doc.setFont(undefined, 'normal');
  doc.text(`${startDate}  →  ${endDate}   ·   Budget $${budget?.toLocaleString()}`, MARGIN, 38);

  doc.setFontSize(8);
  doc.setTextColor(160, 160, 185);
  doc.text('Generated by Roamly · roamly.app', MARGIN, 48);

  y = 65;

  // ── Overview ──────────────────────────────────────────────────────────────
  if (itinerary.overview) {
    heading1('Overview');
    body(itinerary.overview, 0, GREY);
    y += 4;
  }

  // ── Daily Itinerary ───────────────────────────────────────────────────────
  heading1('Day-by-Day Itinerary');

  for (const day of itinerary.dailyItinerary || []) {
    checkY(14);
    // Day header bar
    doc.setFillColor(...LIGHT);
    doc.roundedRect(MARGIN, y - 1, CONTENT, 9, 2, 2, 'F');
    doc.setFontSize(11);
    doc.setTextColor(...PURPLE);
    doc.setFont(undefined, 'bold');
    doc.text(`Day ${day.day}  —  ${day.theme}`, MARGIN + 3, y + 5.5);
    doc.setFontSize(8.5);
    doc.setTextColor(...GREY);
    doc.setFont(undefined, 'normal');
    doc.text(day.date || '', PAGE_W - MARGIN - doc.getTextWidth(day.date || ''), y + 5.5);
    y += 13;

    for (const act of day.activities || []) {
      checkY(16);
      // Time pill
      if (act.time) {
        doc.setFillColor(240, 235, 255);
        doc.roundedRect(MARGIN, y - 3, 14, 5, 1.5, 1.5, 'F');
        doc.setFontSize(7.5);
        doc.setTextColor(...PURPLE);
        doc.setFont(undefined, 'bold');
        doc.text(act.time, MARGIN + 1.5, y + 0.5);
      }

      const nameX = MARGIN + 17;
      doc.setFontSize(9.5);
      doc.setTextColor(...DARK);
      doc.setFont(undefined, 'bold');
      const nameLines = doc.splitTextToSize(act.activity || '', CONTENT - 17 - 22);
      doc.text(nameLines, nameX, y + 0.5);

      if (act.estimatedCost) {
        const costX = PAGE_W - MARGIN - doc.getTextWidth(act.estimatedCost) - 1;
        doc.setFontSize(8.5);
        doc.setTextColor(16, 185, 129);
        doc.setFont(undefined, 'bold');
        doc.text(act.estimatedCost, costX, y + 0.5);
      }

      y += nameLines.length * 4.5;

      if (act.location) {
        body(`📍 ${act.location}`, 17, GREY);
      }
      if (act.description) {
        body(act.description, 17, [130, 130, 150]);
      }
      y += 2;
    }
    y += 3;
  }

  // ── Budget Breakdown ──────────────────────────────────────────────────────
  if (itinerary.budgetBreakdown) {
    divider();
    heading1('Budget Breakdown');
    const bd = itinerary.budgetBreakdown;
    const rows = [
      ['Accommodation', bd.accommodation],
      ['Food & Dining', bd.food],
      ['Activities',    bd.activities],
      ['Transport',     bd.transport],
      ['Miscellaneous', bd.miscellaneous],
    ].filter(r => r[1]);

    for (const [label, value] of rows) {
      checkY(7);
      doc.setFontSize(9.5);
      doc.setTextColor(...DARK);
      doc.setFont(undefined, 'normal');
      doc.text(label, MARGIN, y);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(...PURPLE);
      doc.text(value, PAGE_W - MARGIN - doc.getTextWidth(value), y);
      y += 5.5;
    }
    if (bd.total) {
      checkY(8);
      doc.setDrawColor(...PURPLE);
      doc.setLineWidth(0.4);
      doc.line(MARGIN, y, PAGE_W - MARGIN, y);
      y += 4;
      doc.setFontSize(11);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(...DARK);
      doc.text('Total', MARGIN, y);
      doc.setTextColor(...PURPLE);
      doc.text(bd.total, PAGE_W - MARGIN - doc.getTextWidth(bd.total), y);
      y += 7;
    }
  }

  // ── Practical Tips ────────────────────────────────────────────────────────
  if (itinerary.practicalTips?.length) {
    divider();
    heading1('Practical Tips');
    for (const tip of itinerary.practicalTips) {
      body(`• ${tip}`, 2, GREY);
    }
  }

  // ── Key Phrases ───────────────────────────────────────────────────────────
  if (itinerary.keyPhrases?.length) {
    newPage();
    heading1('Useful Phrases');
    for (const p of itinerary.keyPhrases) {
      checkY(10);
      doc.setFontSize(9.5);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(...DARK);
      doc.text(p.english, MARGIN, y);
      doc.setFont(undefined, 'normal');
      doc.setTextColor(...PURPLE);
      doc.text(p.local, MARGIN + 60, y);
      doc.setTextColor(...GREY);
      doc.setFontSize(8);
      doc.text(p.pronunciation ? `(${p.pronunciation})` : '', MARGIN + 110, y);
      y += 5.5;
    }
  }

  // Footer on every page
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setTextColor(...GREY);
    doc.setFont(undefined, 'normal');
    doc.text(`Roamly · ${itinerary.destination || destination}`, MARGIN, PH - 8);
    doc.text(`${i} / ${pageCount}`, PAGE_W - MARGIN - 10, PH - 8);
  }

  const filename = `${(destination || 'trip').replace(/[^a-z0-9]/gi, '-').toLowerCase()}-itinerary.pdf`;
  doc.save(filename);
}
